import frappe
from frappe.custom.doctype.custom_field.custom_field import create_custom_fields

def update_custom_fields():
    custom_fields = {
        "Item": [
            dict(fieldname='booking_item',
                 label='Booking Item',
                 fieldtype='Check',
                 insert_after='disabled',
                 print_hide=1),
            dict(fieldname='service_item',
                 label='Service Item',
                 fieldtype='Link',
                 insert_after='booking_item',
                 options='Item',
                 depends_on='eval:doc.booking_item',
                 read_only=0, print_hide=1),
            dict(fieldname='is_service_item',
                 label='Is Service Item',
                 fieldtype='Check',
                 insert_after='service_item',
                 options='Item',
                 depends_on='eval:!doc.booking_item',
                 read_only=0, print_hide=1)
        ],
        "Sales Order Item": [
            dict(fieldname='xyz',
                 fieldtype='Section Break',
                 insert_after='item_name',
                 print_hide=1),
            dict(fieldname='start_date',
                 label='Start Date',
                 fieldtype='Date',
                 insert_after='xyz',
                 read_only=0, print_hide=1),
            dict(fieldname='end_date',
                 label='End Date',
                 fieldtype='Date',
                 insert_after='start_date',
                 read_only=0, print_hide=1),
            dict(fieldname='project_custom',
                 label='Project',
                 fieldtype='Data',
                 insert_after='end_date',
                 read_only=0, print_hide=1),
            dict(fieldname='clm_brk',
                 fieldtype='Column Break',
                 insert_after='project_custom',
                 print_hide=1, collapsible=1),
            dict(fieldname='location',
                 label='Location',
                 fieldtype='Data',
                 insert_after='clm_brk',
                 read_only=0, print_hide=1),
            dict(fieldname='latitude',
                 label='Latitude',
                 fieldtype='Data',
                 insert_after='location',
                 read_only=0, print_hide=1),
            dict(fieldname='longitude',
                 label='Longitude',
                 fieldtype='Data',
                 insert_after='latitude',
                 read_only=0, print_hide=1),
        ],
        "Sales Invoice Item": [
            dict(fieldname='xyz',
                 fieldtype='Section Break',
                 insert_after='customer_item_code',
                 print_hide=1),
            dict(fieldname='start_date',
                 label='Start Date',
                 fieldtype='Date',
                 insert_after='xyz',
                 read_only=0, print_hide=1),
            dict(fieldname='end_date',
                 label='End Date',
                 fieldtype='Date',
                 insert_after='start_date',
                 read_only=0, print_hide=1),
            dict(fieldname='project_custom',
                 label='Project',
                 fieldtype='Data',
                 insert_after='end_date',
                 read_only=0, print_hide=1),
            dict(fieldname='clm_brk',
                 fieldtype='Column Break',
                 insert_after='project_custom',
                 print_hide=1, collapsible=1),
            dict(fieldname='location',
                 label='Location',
                 fieldtype='Data',
                 insert_after='clm_brk',
                 read_only=0, print_hide=1),
            dict(fieldname='latitude',
                 label='Latitude',
                 fieldtype='Data',
                 insert_after='location',
                 read_only=0, print_hide=1),
            dict(fieldname='longitude',
                 label='Longitude',
                 fieldtype='Data',
                 insert_after='latitude',
                 read_only=0, print_hide=1),
        ],
    }

    create_custom_fields(custom_fields)
    frappe.msgprint("Custom Field Updated!")